config/routes.rb
Scoutz::Application.routes.draw do
  get "/ping/#{ENV['PING_KEY']}"   => 'status#ping'
  get "/health/#{ENV['PING_KEY']}" => 'status#health'

  get 'meta_search' => 'meta_search#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations' }
  authenticated :user do
    root to: 'page#redirect_to_dashboard', as: :authenticated_root
  end

  resources :units, only: [:edit, :update, :change_default_unit] do
    resources :events do
      collection do
        get 'calendar'
        get 'last_unit_meeting'
      end
    end
    resources :scouts do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :adults do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :email_messages
    resources :sms_messages
    resources :users
    resources :merit_badges
    resources :health_forms
    resources :sub_units
    resources :email_groups
    resources :pages do
      member do
        delete 'deactivate'
        patch 'activate'
        get 'move_higher'
        get 'move_lower'
        get 'show_admin'
      end
    end
    resources :user_passwords, only: [:edit, :update]
    resources :user_email, only: [:edit, :update]
    collection do
      get 'change_default_unit'
    end
  end

  get 'events/index'
  resources :events do
    resources :event_signups
    resources :email_event_signups
    member do
      get 'email_attendees'
      get 'sms_attendees'
    end
  end

  namespace :ckeditor do
    resources :pictures, only: [:index, :create, :destroy]
    resources :attachment_files, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    get '/user/welcome/edit' => 'welcome#edit'
    put '/user/welcome' => 'welcome#update'
  end

  post 'units/new' => 'units#new'
  resources :sub_units
  resources :event_signups do
    member do
      put 'activity_consent_form'
    end
  end

  get 'page/landing'
  get 'page/terms_of_service'
  get 'page/privacy'
  get 'page/contact'
  get 'page/about'

  get 'sign_up/import'
  get 'sign_up/user'
  get 'sign_up/new_unit'
  post 'sign_up/create_unit'
  get 'sign_up/new_sub_unit'
  post 'sign_up/create_sub_unit'

  get 'unsubscribe/event_reminder_email'
  get 'unsubscribe/weekly_newsletter_email'
  get 'unsubscribe/blast_email'

  put 'sms/send_verification'

  root to: 'page#landing'

end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  layout 'dialog_dark_modal'

  def user
    @unit = Unit.new
  end

  def new_unit
    @unit = Unit.new(unit_type: 'Cub Scouts', unit_number: '999')
    # @unit = Unit.new(unit_params)
    @unit.sub_units.build
  end

  def create_unit
    remove_new_sub_unit_attributes
    @unit = Unit.new(unit_params)
    if @unit.save
      current_user.units << @unit
      redirect_to sign_up_new_sub_unit_path, notice: 'Unit was successfully created.'
    else
      render :new_unit
    end
  end

  def new_sub_unit
  end

  def create_sub_unit
  end

  def import
  end

  private

    def remove_new_sub_unit_attributes
      params[:unit][:sub_units_attributes].delete('new_sub_unit')
    end

    def unit_params
      params.require(:unit).permit(:unit_type, :unit_number, :city, :state, :time_zone, sub_units_attributes: [])
    end

end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/sign_up/import.html.haml
%h1 SignUp#import
%p Find me in app/views/sign_up/import.html.haml

app/views/sign_up/new_sub_unit.html.haml
new sub unit

app/views/sign_up/new_unit.html.haml
= bootstrap_form_for @unit, url: sign_up_create_unit_path do |f|
  .row
    .col-md-6
      .well
        %h2 About your unit
        %p &nbsp;

        = f.select :unit_type, Unit.unit_types, {}, class: 'form-control'
        = f.text_field :unit_number, placeholder: 'ex. 134, 603, 15'
        = f.text_field :city
        = f.select :state, options_for_select(::UsStates.states_array, @unit.state), include_blank: 'Select...'

        = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {}

    .col-md-6
      .well.sub-units
        %h2
          And your
          %span.unit-type-plural= @unit.sub_unit_name.pluralize
        %p &nbsp;

        = f.fields_for :sub_units do |f_sub|
          .row
            .col-md-4.controls.sub-unit
              = f_sub.text_field :name
            .col-md-4
              = f_sub.hidden_field :_destroy
              = link_to 'remove', '#', class: 'btn btn-warning btn-sm remove-sub-unit-button'

        .row
          .col-md-12
            .add-sub-unit
              %span.help-block.sub-unit-type.hidden#cub-scouts ex. Den 1, Den 9, Den 11
              %span.help-block.sub-unit-type.hidden#boy-scouts ex. Dragons, Eagles, Sea Cucumbers
              %span.help-block.sub-unit-type.hidden#girl-scouts ex. Patrol 1, Buffalo Gals, Copperheads
              %span.help-block.sub-unit-type.hidden#venturing-crew ex. Team Eagles, Team 1
              %span.help-block.sub-unit-type.hidden#order-of-the-arrow ex. Patrol 1, Crouching Tigers
              %br
              = link_to '#', class: 'btn btn-primary add-sub-unit-button' do
                add a
                %span.unit-type= @unit.sub_unit_name

          .hidden#new-sub-unit-fields
            = f.fields_for :sub_units, SubUnit.new, child_index: 'new_sub_unit' do |f_sub|
              .form-group
                = f_sub.label :name, class: 'control-label col-md-4'
                .col-md-4.controls.sub-unit
                  = f_sub.text_field :name, class: 'form-control'
                .col-md-4
                  = f_sub.hidden_field :_destroy
                  = link_to 'remove', '#', class: 'btn btn-warning btn-sm remove-sub-unit-button'

  .row
    .col-md-12.centered
      = link_to 'Create My Unit', '#', class: 'btn btn-primary create-my-unit'
      = link_to t('.cancel', default: t('helpers.links.cancel')), units_path, class: 'btn btn-default'

:javascript
  window.unit_types = "#{j Unit.unit_types_sub_units.to_json}";

app/views/sign_up/user.html.haml
.row
  .col-md-12
    %h2.centered Welcome to Scoutt.in!
    %p &nbsp;

.row
  .col-md-4.col-md-offset-1
    .well.well-lg
      %h3 Transfer My Scoutander Info
      %p We can transfer all your adults, scouts, and events right from Scoutlander into Scoutz. All you need is any <em>administrator's</em> email address and password.
      .pull-right
        = link_to 'read more...', '#', { data: { toggle: 'modal', target: '#import-more-info' } }
      %p
        %strong Transfer today!

      %p.clearfix

      = bootstrap_form_tag url: '#' do |sf|
        = sf.text_field :sl_admin_email, hide_label: true, class: 'input-lg', placeholder: 'scoutlander admin email'
        = sf.text_field :sl_admin_password, hide_label: true, class: 'input-lg', placeholder: 'scoutlander admin password'
        = submit_tag 'Import', class: 'btn btn-primary btn-block'


  .col-md-4.col-md-offset-1
    .well.well-lg
      %h3 Setup My New Unit
      %p If you don't use Scoutlander, or you just want to start off fresh, you are in the right spot.
      %p &nbsp;
      = bootstrap_form_for @unit, url: sign_up_new_unit_path, method: :get do |f|
        = f.select :unit_type, Unit.unit_types
        = f.text_field :unit_number, placeholder: 'ex. 134, 603, 15'
        = f.submit 'Start My Unit', class: 'btn btn-primary btn-block'


.modal.fade#import-more-info
  .modal-dialog
    .modal-content

      .modal-header
        %button.close{ data: { dismiss: 'modal' } } &times;
        %h3
          Importing from Scoutlander
          %small how does it work?
      .modal-body
        %p Importing from Scoutlander takes place in the background, while you do other things. If Scoutt.in runs into an error, we will notify you. When the import is done, you will receive an email detailing your successful tansfer.
        %p Because we can not import passwords, you will be given the option of sending emails to all your adults and youth, instructing them how to start using Scoutz.
        %p We can import the following:
        %ul
          %li All Adults (no passwords)
          %li All Youth (no passwords)
          %li All Events (last month, + 6 months)

        %p What we can not import:
        %ul
          %li Private site pages
          %li Pictures
          %li Knowledge base documents
          %li Past send emails

      .modal-footer
        = link_to 'Close', '#', class: 'btn btn-default', data: { dismiss: 'modal' }