config/routes.rb
Scoutz::Application.routes.draw do
  get "/ping/#{ENV['PING_KEY']}"   => 'status#ping'
  get "/health/#{ENV['PING_KEY']}" => 'status#health'

  get 'meta_search' => 'meta_search#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations' }
  authenticated :user do
    root to: 'page#redirect_to_dashboard', as: :authenticated_root
  end

  resources :units, only: [:edit, :update, :change_default_unit] do
    resources :events do
      collection do
        get 'calendar'
        get 'last_unit_meeting'
      end
    end
    resources :scouts do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :adults do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :email_messages
    resources :sms_messages
    resources :users
    resources :merit_badges
    resources :health_forms
    resources :sub_units
    resources :email_groups
    resources :pages do
      member do
        delete 'deactivate'
        patch 'activate'
        get 'move_higher'
        get 'move_lower'
        get 'show_admin'
      end
    end
    resources :user_passwords, only: [:edit, :update]
    resources :user_email, only: [:edit, :update]
    collection do
      get 'change_default_unit'
    end
  end

  get 'events/index'
  resources :events do
    resources :event_signups
    resources :email_event_signups
    member do
      get 'email_attendees'
      get 'sms_attendees'
    end
  end

  namespace :ckeditor do
    resources :pictures, only: [:index, :create, :destroy]
    resources :attachment_files, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    get '/user/welcome/edit' => 'welcome#edit'
    put '/user/welcome' => 'welcome#update'
  end

  post 'units/new' => 'units#new'
  resources :sub_units
  resources :event_signups do
    member do
      put 'activity_consent_form'
    end
  end

  get 'page/landing'
  get 'page/terms_of_service'
  get 'page/privacy'
  get 'page/contact'
  get 'page/about'

  get 'sign_up/import'
  get 'sign_up/user'
  get 'sign_up/new_unit'
  post 'sign_up/create_unit'
  get 'sign_up/new_sub_unit'
  post 'sign_up/create_sub_unit'

  get 'unsubscribe/event_reminder_email'
  get 'unsubscribe/weekly_newsletter_email'
  get 'unsubscribe/blast_email'

  put 'sms/send_verification'

  root to: 'page#landing'

end

app/models/email_message.rb
class EmailMessage < ActiveRecord::Base
  include SendToOptions
  include SubUnitIds
  include AttributeSanitizer
  include Deactivatable

  serialize :sub_unit_ids, Array
  serialize :sent_to_hash, Hash

  belongs_to :sender, class_name: 'User', foreign_key: 'user_id'
  belongs_to :unit
  belongs_to :email_group
  has_many :email_attachments, dependent: :destroy
  has_and_belongs_to_many :events
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :email_attachments, allow_destroy: true, reject_if: proc { |a| a['attachment'].blank? }


  validates :message, presence: true, if: :has_no_events?
  validates :subject, presence: true
  validates_associated :email_attachments

  sanitize_attributes :message

  validate :has_selected_users, if: :send_to_users?
  def has_selected_users
    errors.add(:base, 'You must select at least 1 adult or scout recipient') if user_ids.empty?
  end

  validate :has_selected_email_group, if: :send_to_group?
  def has_selected_email_group
    errors.add(:base, 'You must select an email group') if email_group.blank?
  end

  before_create :ensure_id_token



  def has_attachments?
    self.email_attachments.count > 0
  end

  def events_have_signup?
    self.events.where(signup_required: true).count > 0
  end

  def has_events?
    self.events.count > 0
  end


  def sent_to_count
    sent_to_hash.size
  end


  def subject_with_unit
    "#{subject} #{self.unit.email_name}"
  end

  def recipients
    @recipients ||= case send_to_option
                    when 1
                      self.unit.users.gets_email_blast
                    when 2
                      self.unit.users.unit_leaders(self.unit).gets_email_blast
                    when 3
                      # su_users = []
                      # sub_units.each { |su| su_users << su.users_receiving_email_blast }
                      # su_users.flatten
                      sub_units.inject([]) { |users, su| users + su.users_receiving_email_blast }.uniq
                    when 4
                      # self.users.gets_email_blast
                      User.unit_users_with_adults(unit: unit, users_ids: users.pluck(:id)).gets_email_blast
                    when 5
                      self.unit.scoutmasters.gets_email_blast
                    when 8
                      self.email_group.users_with_adults.gets_email_blast

                    else
                      []
                    end
  end

  def recipients_emails
    recipients.map(&:email).uniq
  end

  def recipients_ids
    recipients.map(&:id)
  end

  def sent_to
    User.where(id: sent_to_hash.keys).by_name_lf
  end

  def add_sent_confirmation!(user:, status: 'ok')
    self.sent_to_hash[user.id] = {
      sent_at: Time.zone.now.iso8601,
      status: status
    }
    save(validate: false)
  end



  # scopes
  scope :by_updated_at, -> { order(updated_at: :desc) }

  protected

    def has_no_events?
      if self.persisted?
        has_events?
      else
        self.event_ids.empty?
      end
    end

  private

    def ensure_id_token
      self.id_token = valid_token
    end

    def valid_token
      loop do
        rand_token = generate_token
        break rand_token unless EmailMessage.where(id_token: rand_token).first
      end
    end

    def generate_token
      SecureRandom.urlsafe_base64(12) # .tr('+/=lIO0', 'pqrsxyz')
    end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  mount_uploader :consent_form, ConsentFormUploader

  before_save :update_consent_form_attributes
  # before_create :save_original_filename

  serialize :health_form_coordinator_ids, Array

  has_and_belongs_to_many :users
  # has_many :scouts, through: :users
  # has_many :adults, through: :users
  # has_many :scouts, through: :users, source: :scouts
  has_many :events, dependent: :destroy
  has_many :email_messages, dependent: :destroy
  has_many :sms_messages, dependent: :destroy
  has_many :health_forms, dependent: :destroy
  has_many :pages, -> { order(deactivated_at: :desc, position: :asc) }, dependent: :destroy
  has_many :pictures, class_name: 'Ckeditor::Picture', dependent: :destroy
  has_many :attachment_files, class_name: 'Ckeditor::AttachmentFile', dependent: :destroy
  has_many :email_groups, dependent: :destroy

  has_many :sub_units, dependent: :destroy
  accepts_nested_attributes_for :sub_units, allow_destroy: true, reject_if: proc { |a| a['name'].blank? }


  validates :unit_type, :unit_number, :time_zone, :state, :city, presence: true
  validates :sl_uid, uniqueness: { allow_nil: true }


  validate :consent_form_size_validation, if: 'consent_form?'
  def consent_form_size_validation
    errors.add(:consent_form, 'should be less than 1M') if consent_form.size > 1.0.megabytes.to_i
  end

  validates :url_consent_form, presence: true,  if: Proc.new { |u| u.attach_consent_form && u.use_consent_form == 2 }
  validates :consent_form, presence: true, if: Proc.new { |u| u.attach_consent_form && u.use_consent_form == 3 }



  # example: "Cub Scout Pack 134", "Boy Scout Troop 603"
  def name
    "#{unit_type.singularize} #{unit_type_title} #{unit_number}"
  end

  # example: "CS Pack 134", "BS Troop 603"
  def name_short
    "#{unit_type_short} #{unit_type_title} #{unit_number}"
  end

  # example: "Pack 134", "Troop 603"
  def name_unit
    "#{unit_type_title} #{unit_number}"
  end

  # example: "[CS Pack 134]", "[BS Troop 603]"
  def email_name
    "[#{unit_type_short} #{unit_type_title} #{unit_number}]"
  end




  def scouts
    self.users.where(type: 'Scout')
  end

  def adults
    self.users.where(type: 'Adult')
  end




  def scout_rank_count
    @scout_rank_count ||= self.scouts.group(:rank).count
  end

  def scout_sub_unit_count
    @scout_sub_unit_count ||= self.scouts.joins(:sub_unit).group('"sub_units"."name"').count
  end




  # example: :cub_scouts, :boy_scouts
  def unit_type_to_sym
    @unit_type_to_sym ||= unit_type.gsub(/ /, '').underscore.to_sym
  end

  # example: "CS", "BS"
  def unit_type_short
    @unit_type_short ||= AppConstants.unit_types[unit_type_to_sym][:short_name]
  end

  # example: "Pack", "Troop"
  def unit_type_title
    @unit_type_title ||= AppConstants.unit_types[unit_type_to_sym][:title]
  end

  # example: "Den", "Patrol"
  def sub_unit_name
    @sub_unit_name ||= AppConstants.unit_types[unit_type_to_sym][:sub_unit_name]
  end

  def ranks
    @ranks ||= AppConstants.unit_types[unit_type_to_sym][:ranks]
  end

  def scout_leadership_positions
    @scout_leadership_positions ||= AppConstants.unit_types[unit_type_to_sym][:scout_leadership_positions]
  end

  def adult_leadership_positions
    @adult_leadership_positions ||= AppConstants.unit_types[unit_type_to_sym][:adult_leadership_positions]
  end

  def event_kinds
    AppConstants.unit_types[unit_type_to_sym][:event_types]
  end

  # def url_consent_form
  #   url = case use_consent_form
  #   when 1
  #     "http://www.scouting.org/filestore/pdf/19-673.pdf"
  #   when 2
  #     url_consent_form
  #   when 3
  #     return nil unless consent_form.present?
  #     Rails.configuration.action_mailer.asset_host + consent_form.url
  #   end
  # end


  def scoutmasters
    users.joins(:unit_positions).where("unit_positions.leadership ILIKE '%scoutmaster%'")
  end

  # def committee_members
  #   adult_leadership_positions
  #   committee_types_iliked = ['name1', 'name2'].map { |val| "%#{val}%" }
  #   where('name ILIKE ANY ( array[?] )', myarray_with_percetage_signs)
  # end


  def self.unit_types
    @@unit_types ||= AppConstants.unit_types.keys.map { |e| AppConstants.unit_types[e][:name] }
  end

  def self.unit_types_sub_units
    h = Hash.new
    # @@unit_types ||= AppConstants.unit_types.keys.each { |e| h[AppConstants.unit_types[e][:name]] = AppConstants.unit_types[e][:sub_unit_name] }
    AppConstants.unit_types.keys.each { |e| h[AppConstants.unit_types[e][:name]] = AppConstants.unit_types[e][:sub_unit_name] }
    h
    # SUB_UNIT_TYPES.keys
  end




  def health_form_coordinators
    if has_heath_form_coordinators
      # adults in the form_coordinators_ids list, or an admin
      # t = User.arel_table
      # unit.adults.where(t[:id].in(form_coordinator_ids.reject(&:empty?)).or(t[:role].gteq(User.roles[:admin])))
      self.adults.where(id: health_form_coordinator_ids.reject(&:empty?))
    else
      self.adults.role_is_leader_or_above
    end
  end

  def has_heath_form_coordinators
    !health_form_coordinator_ids.reject(&:empty?).empty?
  end



  ## scopes
  def activities
    PublicActivity::Activity.where(unit_id: self.id).order('created_at DESC')
    # Unit.all
  end



  private

    # def save_original_filename
    #   puts "consent_form present: #{consent_form.present?}"
    #   if consent_form.present?
    #   end
    # end

    def update_consent_form_attributes
      return unless consent_form.present? && consent_form_changed?
      self.consent_form_original_file_name = consent_form.file.original_filename
      self.consent_form_updated_at = Time.zone.now
      self.consent_form_content_type = consent_form.file.content_type
      self.consent_form_file_size = consent_form.file.size
    end

end

app/controllers/email_messages_controller.rb
class EmailMessagesController < ApplicationController
  # etag { current_user.try :id }

  before_action :auth_and_time_zone
  before_action :set_email_message, only: [:show, :edit, :update, :destroy]
  before_action :set_send_to_lists, only: [:new, :edit, :update]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    # authorize EmailMessage
    @email_messages = policy_scope(EmailMessage.where(unit_id: @unit)).includes(:sender).page(params[:page]).per(20).by_updated_at
    # fresh_when etag: current_user.try(:id), last_modified: @email_messages.maximum(:updated_at)
  end

  def show
    authorize @email_message
    # fresh_when(@email_message)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    options = {}
    options.merge!(send_to_option: 4, user_ids: params[:user_ids].split(',')) if params[:user_ids]
    options.merge!(event_ids: params[:event_ids].split(',')) if params[:event_ids]
    options.merge!(send_to_option: 8, email_group_id: params[:email_group_id]) if params[:email_group_id]
    @email_message = EmailMessage.new(options)
    authorize @email_message
  end

  def edit
    authorize @email_message
  end

  def create
    remove_new_email_attachment_attribute
    @email_message = @unit.email_messages.build(email_message_params)
    authorize @email_message

    if @email_message.save
      current_user.email_messages << @email_message
      if params[:commit] == 'Delay 15 Minutes'
        EmailMessagesJob.set(wait: 15.minutes).perform_later(@email_message)
        flash[:notice] = 'Email message is queued to be sent in 15 minutes.'
      else
        EmailMessagesJob.perform_later(@email_message)
        flash[:notice] = 'Email message was queued to be sent.'
      end
      redirect_to unit_email_message_path(@unit, @email_message)
    else
      set_send_to_lists
      render action: 'new'
    end
  end

  def update
    authorize @email_message
    remove_new_email_attachment_attribute
    if @email_message.update_attributes(email_message_params)
      redirect_to unit_email_message_path(@unit, @email_message), notice: 'Email message was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    authorize @email_message
    if @email_message.sent_at.nil?
      @email_message.deactivate!
      flash[:notice] = "Sending of email '#{@email_message.subject}' cancelled."
    else
      flash[:notice] = "I'm sorry, but the email '#{@email_message.subject}' was already sent at #{@email_message.sent_at.to_s(:long_ampm)}."
    end

    if params[:view] == 'show'
      redirect_to unit_email_message_url(@unit, @email_message)
    else
      redirect_to unit_email_messages_url(@unit)
    end
  end


  private

    def set_email_message
      # @email_message = EmailMessage.find(params[:id])
      @email_message = @unit.email_messages.where(id: params[:id]).first!
    end

    def set_send_to_lists
      @leaders = @unit.users.unit_leaders(@unit).gets_email_blast.by_name_lf
      @sub_units = @unit.sub_units.by_name
      @unit_users = @unit.users.gets_email_blast.by_name_lf
    end

    def remove_new_email_attachment_attribute
      return unless params[:email_message][:email_attachments_attributes]
      params[:email_message][:email_attachments_attributes].delete('new_email_attachment')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_message_params
      params.require(:email_message).permit(:message, :subject, :user_id, { email_attachments_attributes: [:id, :attachment, :_destroy] }, { sub_unit_ids: [] }, { event_ids: [] }, { user_ids: [] }, :send_to_option, :email_group_id)
      # filter_params(params[:email_message])
    end

    def filter_params(params)
      case params[:send_to_option]
      when '1', '2' # entire unit or all leaders
        params.except(:sub_unit_ids, :user_ids)
      when '3' # selected sub_units
        params.except(:user_ids)
      when '4' # selected users
        params.except(:sub_unit_ids)
      when '8' # email group
        params.except(:email_group_id)
      end
    end

end

app/helpers/email_messages_helper.rb
module EmailMessagesHelper
  def sub_unit_emails(sub_unit)
    sub_unit.users_receiving_email_blast.map(&:name_email).join(', ')
  end

  def sub_unit_sms(sub_unit)
    sub_unit.users_receiving_sms_blast.map(&:name_sms).join(', ')
  end

  def recipient_display(email_message)
    case email_message.send_to_option
    when 1
      "#{email_message.send_to} "
    when 2
      email_message.sub_units.map(&:name).join(', ')
    when 3
      msg = ''
      msg += email_message.send_to
      msg += '<br/>'
      msg += email_message.recipients.map(&:name_email).join('<br/>')
      msg.html_safe
    end
  end

  def email_message_date_subject(email_message)
    if email_message.sent_at.nil?
      email_message.subject
    else
      "#{Google::TimeDisplay.new(email_message.sent_at).abbr_month} • #{email_message.subject}"
    end
  end
end

app/views/email_messages/_form.html.haml
= bootstrap_form_for @email_message, url: unit_email_messages_path(@unit), html: { multipart: true } do |f|
  = f.hidden_field :unit_id, value: @unit.id
  = f.hidden_field :user_id, value: current_user.id

  = render partial: 'layouts/flash', locals: { flash: flash, ar_object: @email_message }

  .row
    .col-md-3
      = f.select :send_to_option, EmailMessage.send_to_options(@unit), label: 'Send to'

  .row
    .col-md-10.col-md-offset-1
      .collapse#email-group-list{ class: ('in' if @email_message.send_to_group?) }
        .well.well-sm
          .row
            .col-md-4
              = f.collection_select :email_group_id, @unit.email_groups, :id, :name, { label: 'Group', prompt: 'Select...' }, class: 'form-control'


            .col-md-8
              - @unit.email_groups.each do |email_group|
                .email-groups{ id: "email-group-#{email_group.id}", class: ('hidden' unless @email_message.email_group_id == email_group.id) }
                  %br
                  %p= email_group.description
                  %smaller.text-muted= email_group.users.gets_email_blast.map(&:name_email).join(', ')


      .collapse#email-leaders-list{ class: ('in' if @email_message.send_to_leaders?) }
        .well.well-sm
          %h4 #{@unit.name_unit} Leaders
          %smaller.text-muted= @leaders.map(&:name_email).join(', ')

      .collapse#email-scoutmasters-list{ class: ('in' if @email_message.send_to_scoutmasters?) }
        .well.well-sm
          %h4 Scoutmasters (SM/ASM)
          %smaller.text-muted= @unit.scoutmasters.gets_email_blast.by_name_lf.map(&:name_email).join(', ')

      .collapse#email-sub-unit-list{ class: ('in' if @email_message.send_to_sub_units?) }
        .well.well-sm
          - @sub_units.each do |sub_unit|
            .checkbox
              = f.label :sub_unit, class: 'sub-unit', data: { 'original-title' => sub_unit_emails(sub_unit) } do
                = check_box_tag 'email_message[sub_unit_ids][]', sub_unit.id, @email_message.sub_unit_ids.include?(sub_unit.id.to_s)
                %strong= sub_unit.name
                %smaller.text-muted= sub_unit_emails(sub_unit)

      .collapse#email-send-to-users-list{ class: ('in' if @email_message.send_to_users?) }
        .well.well-sm
          = f.collection_select :user_ids, @unit_users, :id, :name_lf, { hide_label: true }, { multiple: true }



  %fieldset
    %legend Events
    .row
      .col-md-12
        %p Selected events will have signup links at the bottom of the message
    .row
      .col-md-8
        .well.well-sm.email-message-events
          = f.collection_check_boxes :event_ids, @unit.events.from_today.by_start, :id, :list_name, hide_label: true
      .col-md-4
        .alert.alert-info
          %strong Tip:
          Want to send an announcement about an event? Just check the event(s) you want to announce, enter a subject, optional message, and click send. All info about the event(s) will be in the email.



  %fieldset
    %legend Attachments
    %p
      %strong Attach up to 4 files, total size should not exceed 2MB
    %p= button_tag 'Add Attachment', type: 'button', class: 'btn btn-success btn-sm add-attachment'

    #email-attachments

    .hidden#new-attachment-fields
      .email-attachment-fields
        = f.fields_for :email_attachments, EmailAttachment.new, child_index: 'new_email_attachment' do |h_attachment|
          .row
            .col-md-8
              .well.well-sm
                .pull-right= button_tag 'Remove', type: 'button', class: 'btn btn-warning btn-xs remove-attachment'
                %p= h_attachment.file_field :attachment, hide_label: true, control_col: 'col-md-12'


    .help-block alowed attachments: jpg jpeg gif png pdf doc xls docx xls xlsx xlsb rtf odf ppt txt csv
    .help-block size: each attachment must be < 1MB
    %small.text-muted attachments are saved for 6 months, then deleted



  %fieldset
    %legend Message
    .row
      .col-md-6
        %p
          From:
          %span.large.label.label-default= current_user.email
      .col-md-6
        %p.pull-right Use #{ button_tag 'Add Attachment', type: 'button', class: 'btn btn-success btn-xs add-attachment' } above to attach files. Use #{ image_tag 'ckeditor_image_button.png' } to insert images.
    .row
      .col-md-12
        = f.text_field :subject, hide_label: true, control_col: 'col-md-10', placeholder: 'subject'
        %p= f.text_area :message, id: 'ckeditor', hide_label: true, control_col: 'col-md-10'



  %br
  -# = f.primary 'Send Email Blast'
  = button_tag 'Send Email Blast', type: 'button', class: 'btn btn-primary', data: { toggle: 'modal', target: '#send-email-blast' }
  = link_to 'Cancel', unit_email_messages_path(@unit), class: 'btn btn-default'


  .modal.fade#send-email-blast
    .modal-dialog
      .modal-content
        .modal-header
          %h4.modal-title Send Email Blast

        .modal-body
          %p
            %strong We recommend delaying your email for 15 minutes.
          %p Just in case you forgot something, or made a mistake, you can cancel the sending.

        .modal-footer
          = button_tag 'Cancel', type: 'button', data: { dismiss: 'modal' }, class: 'btn btn-default'
          = f.submit 'Send Now!', class: 'btn btn-default'
          = f.submit 'Delay 15 Minutes', class: 'btn btn-primary'

app/views/email_messages/_sent_to_details.html.haml
%small
  - email_message.sent_to.each do |user|
    = unit_user_link(email_message.unit, user)
    &mdash;
    = Time.zone.parse(email_message.sent_to_hash[user.id][:sent_at]).to_s(:datetimepicker)
    , status:
    = email_message.sent_to_hash[user.id][:status]
    %br

app/views/email_messages/edit.html.haml
.page-header
  %h2 Edit Email in #{@unit.name}

= render 'form'

app/views/email_messages/index.html.haml
.page-header
  .row
    .col-md-8
      %h2
        %i.fa.fa-envelope
        My Sent Messages (#{@unit.name_unit})

    .col-md-4.right-aligned
      - if policy(EmailMessage).create?
        = link_to(new_unit_email_message_path(@unit), class: 'btn btn-default') do
          %i.fa.fa-plus
          New Email Blast


= render partial: 'layouts/flash', locals: { flash: flash }

%table.table
  %thead
    %th Sent
    %th Subject
    %th.hidden-xs From
    %th Recipients
    %th Actions

  - @email_messages.each do |email_message|
    %tr
      %td
        - if email_message.sent_at
          = email_message.sent_at.to_s(:short_ampm)
        - elsif email_message.deactivated?
          cancelled
        - else
          %em pending

      %td
        = link_to email_message.subject, unit_email_message_path(@unit, email_message)
        - if email_message.has_attachments?
          %i.fa.fa-paper-clip

      %td.hidden-xs= email_message.sender.email

      %td
        = email_message.send_to
        %span.badge= email_message.recipients_ids.size

      %td
        .btn-group
          = link_to 'View', unit_email_message_path(@unit, email_message), class: 'btn btn-default btn-xs'
          - if email_message.sent_at.nil? && email_message.active? && policy(email_message).destroy?
            = link_to 'Cancel Sending', unit_email_message_path(@unit, email_message), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'

= paginate @email_messages, theme: 'bootstrap'

%p
  %em.text-muted email messages are stored for about 1.5 years

app/views/email_messages/new.html.haml
.page-header
  %h2 New Email for #{@unit.name}

= render 'form'

app/views/email_messages/show.html.haml
.page-header
  .row
    .col-md-7
      %h2 Email Message

    .col-md-5.right-aligned
      .btn-group
        = link_to unit_email_messages_path(@unit), class: 'btn btn-default' do
          %i.fa.fa-reply.hidden-xs
          Sent Emails

        - if policy(EmailMessage).create?
          = link_to new_unit_email_message_path(@unit), class: 'btn btn-default' do
            %i.fa.fa-plus.hidden-xs
            New Email Blast

        - if @email_message.sent_at.nil? && @email_message.active? && policy(@email_message).destroy?
          = link_to unit_email_message_path(@unit, @email_message, view: 'show'), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
            %i.fa.fa-trash
            Cancel Sending


= render partial: 'layouts/flash', locals: { flash: flash, ar_object: @email_message }

.text-xlarge
  %table.table
    %tr
      %td
        %strong Subject
      %td= @email_message.subject

    %tr
      %td
        %strong From
      %td= @email_message.sender.name_email

    - if policy(@email_message).show_recipients?
      %tr
        %td
          %strong Recipients
        %td
          = @email_message.send_to
          %span.badge= @email_message.sent_to_count
          - if @email_message.send_to_option == 3
            (
            %small>
              %em>= @email_message.sub_units.map(&:name).join(', ')
            )

          %br
          #sent-to-details
            %p= unit_users_link_list(@email_message.unit, @email_message.sent_to)
          %p.small
            = link_to unit_email_message_path(@unit, @email_message), remote: true, id: 'details-reveal' do
              %i.fa.fa-caret-square-o-right
              show details...

    %tr
      %td
        %strong Sent
      %td
        - if @email_message.sent_at
          = @email_message.sent_at.to_s(:long_ampm)
        - elsif @email_message.deactivated?
          sending cancelled at #{ @email_message.deactivated_at.to_s(:long_ampm) }
        - else
          currently in queue

    %tr
      %td
        %strong Events
      %td
        - if @email_message.events.size > 0
          - @email_message.events.each do |event|
            = link_to event.list_name, unit_event_path(@unit, event)
            %br
        - else
          %em none selected

    %tr
      %td
        %strong Attachments*
      %td
        - @email_message.email_attachments.each do |email_attachment|
          = link_to email_attachment.original_file_name, email_attachment.attachment.url, target: '_blank'
          %br

    %tr
      %td
        %strong Message
      %td
        .show-message= @email_message.message.html_safe
%small.text-muted * attachments are saved for 6 months, then deleted

app/views/email_messages/show.js.haml
:plain
  $("a#details-reveal").hide();
  $("div#sent-to-details").html("#{escape_javascript(render partial: 'sent_to_details', locals: {email_message: @email_message})}");