config/routes.rb
Scoutz::Application.routes.draw do
  get "/ping/#{ENV['PING_KEY']}"   => 'status#ping'
  get "/health/#{ENV['PING_KEY']}" => 'status#health'

  get 'meta_search' => 'meta_search#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations' }
  authenticated :user do
    root to: 'page#redirect_to_dashboard', as: :authenticated_root
  end

  resources :units, only: [:edit, :update, :change_default_unit] do
    resources :events do
      collection do
        get 'calendar'
        get 'last_unit_meeting'
      end
    end
    resources :scouts do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :adults do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :email_messages
    resources :sms_messages
    resources :users
    resources :merit_badges
    resources :health_forms
    resources :sub_units
    resources :email_groups
    resources :pages do
      member do
        delete 'deactivate'
        patch 'activate'
        get 'move_higher'
        get 'move_lower'
        get 'show_admin'
      end
    end
    resources :user_passwords, only: [:edit, :update]
    resources :user_email, only: [:edit, :update]
    collection do
      get 'change_default_unit'
    end
  end

  get 'events/index'
  resources :events do
    resources :event_signups
    resources :email_event_signups
    member do
      get 'email_attendees'
      get 'sms_attendees'
    end
  end

  namespace :ckeditor do
    resources :pictures, only: [:index, :create, :destroy]
    resources :attachment_files, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    get '/user/welcome/edit' => 'welcome#edit'
    put '/user/welcome' => 'welcome#update'
  end

  post 'units/new' => 'units#new'
  resources :sub_units
  resources :event_signups do
    member do
      put 'activity_consent_form'
    end
  end

  get 'page/landing'
  get 'page/terms_of_service'
  get 'page/privacy'
  get 'page/contact'
  get 'page/about'

  get 'sign_up/import'
  get 'sign_up/user'
  get 'sign_up/new_unit'
  post 'sign_up/create_unit'
  get 'sign_up/new_sub_unit'
  post 'sign_up/create_sub_unit'

  get 'unsubscribe/event_reminder_email'
  get 'unsubscribe/weekly_newsletter_email'
  get 'unsubscribe/blast_email'

  put 'sms/send_verification'

  root to: 'page#landing'

end

app/models/scout.rb
class Scout < User
  has_many :event_signups, dependent: :destroy

  def unit_adults(unit)
    self.adults.joins(:units).where(units: { id: unit })
  end

  # when scouts view other scouts records
  def unit_scouts(_unit)
    Scout.where(id: self.id)
  end


  # from an adult, find all scouts, and other adults related through those scouts
  def unit_family(unit)
    adult_ids = unit_adults(unit).pluck(:id)
    scout_ids = Scout.joins(:adults).where(user_relationships: { adult_id: adult_ids })
                     .joins(:units).where(units: { id: unit })
                     .pluck(:id)
    user_ids = (adult_ids + scout_ids) << self.id
    User.where(id: user_ids)
  end



  def has_adult?(user)
    self.adults.where(id: user).exists?
  end



  def self.meta_search(unit_scope: nil, keywords:)
    meta_users = unit_scope.nil? ? Scout.all : unit_scope.scouts
    meta_users.pg_meta_search(keywords)
  end


  def meta_search_json(unit_scope:)
    { resource: 'scout',
      initials: initials,
      id: id,
      name: name,
      desc: [rank, sub_unit.try(:name)].join(' - ') || '&nbsp;',
      url: Rails.application.routes.url_helpers.unit_scout_path(unit_scope, id)
    }
  end

end

app/controllers/scouts_controller.rb
class ScoutsController < UsersController

  def index
    authorize Scout
    @users = @unit.scouts.includes(:sub_unit, :adults).by_name_lf
    @users_count = @unit.scouts.count
    if params[:search_typeahead] && !params[:search_typeahead].blank?
      @users = @users.name_contains(params[:search_typeahead])
      @searching = true
    end

    # fresh_when last_modified: @users.maximum(:updated_at)
  end

  def new; super(Scout); end

  def edit
    authorize_scout
  end


  def create
    remove_new_phone_attribute
    @user = Scout.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        @unit.users << @user
        format.html { redirect_to unit_scout_path(@unit, @user), notice: "#{@user.full_name} was successfully created." }
        # format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize_scout
    remove_new_phone_attribute
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to unit_scout_path(@unit, @user), notice: "#{@user.full_name} was successfully updated." }
        # format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @user
    @user.destroy
    user_name = @user.full_name
    respond_to do |format|
      format.html { redirect_to unit_scouts_path(@unit), notice: "#{user_name}, and all associated data, was permanently deleted."  }
      # format.json { head :no_content }
    end
  end

  def send_welcome_reset_password
    super
    redirect_to unit_scout_path(@unit, @user), notice: "Welcome email was sent to #{@user.name}. Their account has been deactivated until they confirm."
  end

  private

    def authorize_scout
      # https://github.com/elabs/pundit/blob/master/lib/pundit.rb
      # basically following the pundit.authorize method
      query = params[:action].to_s + '?'
      @_policy_authorized = true
      @_pundit_policy_authorized = true
      policy = ScoutPolicy.new(current_user, @user, @unit)
      fail Pundit::NotAuthorizedError, 'not allowed to edit this scout' unless policy.public_send(query)
    end

end

app/views/scouts/_index.html.haml
- if users.size > 0
  %table.table.table-outside-bordered
    %thead
      %th
      %th Name
      %th= unit.sub_unit_name
      %th Rank
      %th Leadership
      -# %th.text-right Age
      %th Adults

    = cache_unless searching, ["unit-#{unit.id}", cache_key_for_users(users)] do
      - users.each do |scout|
        = cache ["unit-#{unit.id}", scout] do
          %tr.v-centered
            %td.centered= user_picture_circle(scout)
            %td= link_to scout.name_lf, unit_scout_path(unit, scout)
            %td= scout.sub_unit.try(:name)
            %td= scout.rank
            %td.col-md-2= all_leadership_positions(@unit, scout)
            -# %td.text-right= scout.age
            %td= unit_users_link_list(unit, scout.adults)

  %small showing #{users.size} of #{users_count}

- else
  %h1.centered no results found

app/views/scouts/_index_admin.html.haml
- if users.size > 0
  %table.table.table-outside-bordered
    %thead
      %th
      %th Name
      %th= unit.sub_unit_name
      %th.hidden-xs Rank
      %th Leadership
      %th.text-right.hidden-xs Age
      %th Adults
      %th.hidden-xs{ colspan: 2 } Status

    = cache_unless searching, ["unit-#{unit.id}", :admin, cache_key_for_users(users)] do
      - users.each do |scout|
        = cache ["unit-#{unit.id}", :admin, scout] do
          %tr.v-centered
            %td.centered= user_picture_circle(scout)
            %td= link_to scout.name_lf, unit_scout_path(unit, scout)
            %td= scout.sub_unit.try(:name)
            %td.hidden-xs= scout.rank
            %td.col-md-2= all_leadership_positions(@unit, scout)
            %td.hidden-xs.text-right= scout.age
            %td= unit_users_link_list(unit, scout.adults)
            = render partial: 'users/user_admin_status', locals: { user: scout }

  %small showing #{users.size} of #{users_count}

- else
  %h1.centered no results found

app/views/scouts/edit.html.haml
.page-header
  %h2 Edit Scout

= render 'users/form'

app/views/scouts/index.html.haml
.page-header
  .row
    .col-md-8
      %h2
        %i.fa.fa-user{ style: 'color: #808000;' }
        Scouts in #{@unit.name_unit}

    .col-md-4.right-aligned
      - if policy(Scout).new?
        .pull-right
          = link_to(new_unit_scout_path(@unit), class: 'btn btn-default') do
            %i.fa.fa-plus
            New Scout

.row
  .col-md-9
    = render partial: 'layouts/flash', locals: { flash: flash }

    = cache ["unit-#{@unit.id}", ':scouts_search'] do
      = render partial: 'layouts/search', locals: { type: 'scouts', search_url: "/units/#{@unit.id}/scouts.js?search_typeahead=" }
      %br


    #scout-index
      - if current_user.admin?
        = render partial: 'index_admin', locals: { unit: @unit, users: @users, users_count: @users_count, searching: @searching }
      - else
        = render partial: 'index', locals: { unit: @unit, users: @users, users_count: @users_count, searching: @searching }


  .col-md-3
    = cache ["unit-#{@unit.id}", :rank_count, cache_key_for_users(@users)] do
      .panel.panel-index-table.panel-default
        .panel-heading Rank Count (all)
        .panel-body
          %ul.list-unstyled
            - @unit.ranks.each do |rank|
              %li #{rank} : #{@unit.scout_rank_count[rank]}

    = cache ["unit-#{@unit.id}", :sub_unit_count, cache_key_for_users(@users), cache_key_for_sub_units(@unit.sub_units)] do
      .panel.panel-index-table.panel-default
        .panel-heading #{@unit.sub_unit_name} Count (all)
        .panel-body
          %ul.list-unstyled
            - @unit.scout_sub_unit_count.each do |sub_unit|
              %li #{sub_unit[0] || '<none>'} : #{sub_unit[1]}

app/views/scouts/index.js.haml
- if current_user.admin?
  :plain
    $("div#scout-index").html("#{escape_javascript(render partial: 'scouts/index_admin', locals: {unit: @unit, users: @users, users_count: @users_count, searching: @searching})}");

- else
  :plain
    $("div#scout-index").html("#{escape_javascript(render partial: 'scouts/index', locals: {unit: @unit, users: @users, users_count: @users_count, searching: @searching})}");

app/views/scouts/new.html.haml
.page-header
  %h2 New Scout in #{@unit.name}

= render 'users/form'

app/views/scouts/show.html.haml
.page-header
  .row
    .col-md-7
      %h2 Scout: #{@user.full_name}

    .col-md-5.right-aligned
      .btn-group
        = link_to(unit_scouts_path(@unit), class: 'btn btn-default') do
          %i.fa.fa-reply.hidden-xs
          #{@unit.name_unit} Scouts

        - if ScoutPolicy.new(current_user, @user, @unit).edit?
          = link_to(edit_unit_scout_path(@unit, @user), class: 'btn btn-default') do
            %i.fa.fa-edit.hidden-xs
            Edit

        - if policy(@user).new? || policy(@user).destroy?
          %a.btn.dropdown-toggle.btn-default{ href: '#', data: { toggle: 'dropdown' }, title: 'Actions' }
            %i.fa.fa-gear
            %span.caret
          %ul.dropdown-menu.pull-right
            - if policy(@user).destroy?
              %li
                = link_to(unit_scout_path(@unit, @user), method: :delete, data: { confirm: 'Are you sure?' }, class: '') do
                  %i.fa.fa-trash-o.text-muted-more
                  Destroy #{@user.first_name}

            - if policy(@user).new?
              %li
                = link_to(new_unit_scout_path(@unit), class: '') do
                  %i.fa.fa-plus.text-muted-more
                  New Scout

            - if policy(@user).send_welcome_reset_password?
              %li
                = link_to '#', data: { toggle: 'modal', target: '#send-welcome-email' } do
                  %i.fa.fa-envelope.text-muted-more
                  Send Welcome Email



= render partial: 'layouts/flash', locals: { flash: flash, ar_object: @user }

.row
  = cache ["unit-#{@unit.id}", @user] do
    .col-md-8
      .text-xlarge
        %table.table#user-info
          %tr
            %td
              / %strong= @user.sub_unit.unit.unit_type_title
              %strong Unit
            %td= @unit.name

          %tr
            %td
              %strong Rank
            %td= @user.rank

          %tr
            %td
              %strong Position
            %td= all_leadership_positions(@unit, @user)

          %tr
            %td
              %strong= @unit.sub_unit_name
            %td= @user.sub_unit.try(:name)

          %tr
            %td
              %strong Email
            %td= mail_to @user.try(:email)

          %tr
            %td
              %strong Birthday
            %td= birthdate_and_years_old(@user)

          %tr
            %td
              %strong Phones
            %td
              - @user.phones.each do |phone|
                #{phone.kind}:
                = link_to number_to_phone(phone.number), "tel:1-#{number_to_phone phone.number}"
                %br

          %tr
            %td
              %strong Parents
            %td= unit_users_link_list(@unit, @user.unit_adults(@unit))

          %tr
            %td
              %strong Address
            %td
              %address= user_address_show(@user)

          = render partial: 'users/health_form_show', locals: { user: @user, unit: @unit }


  .col-md-3.col-md-offset-1
    = render partial: 'users/picture_panel_lg', locals: { user: @user }
    - if current_user.admin?
      = render partial: 'users/show_admin_panel', locals: { user: @user }

- if !@user.email.blank? && policy(@user).send_welcome_reset_password?
  = render layout: 'users/send_welcome_email_modal' do
    = link_to 'Send Welcome Email', send_welcome_reset_password_unit_scout_path(@unit, @user), class: 'btn btn-primary'