config/routes.rb
Scoutz::Application.routes.draw do
  get "/ping/#{ENV['PING_KEY']}"   => 'status#ping'
  get "/health/#{ENV['PING_KEY']}" => 'status#health'

  get 'meta_search' => 'meta_search#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations' }
  authenticated :user do
    root to: 'page#redirect_to_dashboard', as: :authenticated_root
  end

  resources :units, only: [:edit, :update, :change_default_unit] do
    resources :events do
      collection do
        get 'calendar'
        get 'last_unit_meeting'
      end
    end
    resources :scouts do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :adults do
      member do
        get 'send_welcome_reset_password'
      end
    end
    resources :email_messages
    resources :sms_messages
    resources :users
    resources :merit_badges
    resources :health_forms
    resources :sub_units
    resources :email_groups
    resources :pages do
      member do
        delete 'deactivate'
        patch 'activate'
        get 'move_higher'
        get 'move_lower'
        get 'show_admin'
      end
    end
    resources :user_passwords, only: [:edit, :update]
    resources :user_email, only: [:edit, :update]
    collection do
      get 'change_default_unit'
    end
  end

  get 'events/index'
  resources :events do
    resources :event_signups
    resources :email_event_signups
    member do
      get 'email_attendees'
      get 'sms_attendees'
    end
  end

  namespace :ckeditor do
    resources :pictures, only: [:index, :create, :destroy]
    resources :attachment_files, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    get '/user/welcome/edit' => 'welcome#edit'
    put '/user/welcome' => 'welcome#update'
  end

  post 'units/new' => 'units#new'
  resources :sub_units
  resources :event_signups do
    member do
      put 'activity_consent_form'
    end
  end

  get 'page/landing'
  get 'page/terms_of_service'
  get 'page/privacy'
  get 'page/contact'
  get 'page/about'

  get 'sign_up/import'
  get 'sign_up/user'
  get 'sign_up/new_unit'
  post 'sign_up/create_unit'
  get 'sign_up/new_sub_unit'
  post 'sign_up/create_sub_unit'

  get 'unsubscribe/event_reminder_email'
  get 'unsubscribe/weekly_newsletter_email'
  get 'unsubscribe/blast_email'

  put 'sms/send_verification'

  root to: 'page#landing'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  mount_uploader :consent_form, ConsentFormUploader

  before_save :update_consent_form_attributes
  # before_create :save_original_filename

  serialize :health_form_coordinator_ids, Array

  has_and_belongs_to_many :users
  # has_many :scouts, through: :users
  # has_many :adults, through: :users
  # has_many :scouts, through: :users, source: :scouts
  has_many :events, dependent: :destroy
  has_many :email_messages, dependent: :destroy
  has_many :sms_messages, dependent: :destroy
  has_many :health_forms, dependent: :destroy
  has_many :pages, -> { order(deactivated_at: :desc, position: :asc) }, dependent: :destroy
  has_many :pictures, class_name: 'Ckeditor::Picture', dependent: :destroy
  has_many :attachment_files, class_name: 'Ckeditor::AttachmentFile', dependent: :destroy
  has_many :email_groups, dependent: :destroy

  has_many :sub_units, dependent: :destroy
  accepts_nested_attributes_for :sub_units, allow_destroy: true, reject_if: proc { |a| a['name'].blank? }


  validates :unit_type, :unit_number, :time_zone, :state, :city, presence: true
  validates :sl_uid, uniqueness: { allow_nil: true }


  validate :consent_form_size_validation, if: 'consent_form?'
  def consent_form_size_validation
    errors.add(:consent_form, 'should be less than 1M') if consent_form.size > 1.0.megabytes.to_i
  end

  validates :url_consent_form, presence: true,  if: Proc.new { |u| u.attach_consent_form && u.use_consent_form == 2 }
  validates :consent_form, presence: true, if: Proc.new { |u| u.attach_consent_form && u.use_consent_form == 3 }



  # example: "Cub Scout Pack 134", "Boy Scout Troop 603"
  def name
    "#{unit_type.singularize} #{unit_type_title} #{unit_number}"
  end

  # example: "CS Pack 134", "BS Troop 603"
  def name_short
    "#{unit_type_short} #{unit_type_title} #{unit_number}"
  end

  # example: "Pack 134", "Troop 603"
  def name_unit
    "#{unit_type_title} #{unit_number}"
  end

  # example: "[CS Pack 134]", "[BS Troop 603]"
  def email_name
    "[#{unit_type_short} #{unit_type_title} #{unit_number}]"
  end




  def scouts
    self.users.where(type: 'Scout')
  end

  def adults
    self.users.where(type: 'Adult')
  end




  def scout_rank_count
    @scout_rank_count ||= self.scouts.group(:rank).count
  end

  def scout_sub_unit_count
    @scout_sub_unit_count ||= self.scouts.joins(:sub_unit).group('"sub_units"."name"').count
  end




  # example: :cub_scouts, :boy_scouts
  def unit_type_to_sym
    @unit_type_to_sym ||= unit_type.gsub(/ /, '').underscore.to_sym
  end

  # example: "CS", "BS"
  def unit_type_short
    @unit_type_short ||= AppConstants.unit_types[unit_type_to_sym][:short_name]
  end

  # example: "Pack", "Troop"
  def unit_type_title
    @unit_type_title ||= AppConstants.unit_types[unit_type_to_sym][:title]
  end

  # example: "Den", "Patrol"
  def sub_unit_name
    @sub_unit_name ||= AppConstants.unit_types[unit_type_to_sym][:sub_unit_name]
  end

  def ranks
    @ranks ||= AppConstants.unit_types[unit_type_to_sym][:ranks]
  end

  def scout_leadership_positions
    @scout_leadership_positions ||= AppConstants.unit_types[unit_type_to_sym][:scout_leadership_positions]
  end

  def adult_leadership_positions
    @adult_leadership_positions ||= AppConstants.unit_types[unit_type_to_sym][:adult_leadership_positions]
  end

  def event_kinds
    AppConstants.unit_types[unit_type_to_sym][:event_types]
  end

  # def url_consent_form
  #   url = case use_consent_form
  #   when 1
  #     "http://www.scouting.org/filestore/pdf/19-673.pdf"
  #   when 2
  #     url_consent_form
  #   when 3
  #     return nil unless consent_form.present?
  #     Rails.configuration.action_mailer.asset_host + consent_form.url
  #   end
  # end


  def scoutmasters
    users.joins(:unit_positions).where("unit_positions.leadership ILIKE '%scoutmaster%'")
  end

  # def committee_members
  #   adult_leadership_positions
  #   committee_types_iliked = ['name1', 'name2'].map { |val| "%#{val}%" }
  #   where('name ILIKE ANY ( array[?] )', myarray_with_percetage_signs)
  # end


  def self.unit_types
    @@unit_types ||= AppConstants.unit_types.keys.map { |e| AppConstants.unit_types[e][:name] }
  end

  def self.unit_types_sub_units
    h = Hash.new
    # @@unit_types ||= AppConstants.unit_types.keys.each { |e| h[AppConstants.unit_types[e][:name]] = AppConstants.unit_types[e][:sub_unit_name] }
    AppConstants.unit_types.keys.each { |e| h[AppConstants.unit_types[e][:name]] = AppConstants.unit_types[e][:sub_unit_name] }
    h
    # SUB_UNIT_TYPES.keys
  end




  def health_form_coordinators
    if has_heath_form_coordinators
      # adults in the form_coordinators_ids list, or an admin
      # t = User.arel_table
      # unit.adults.where(t[:id].in(form_coordinator_ids.reject(&:empty?)).or(t[:role].gteq(User.roles[:admin])))
      self.adults.where(id: health_form_coordinator_ids.reject(&:empty?))
    else
      self.adults.role_is_leader_or_above
    end
  end

  def has_heath_form_coordinators
    !health_form_coordinator_ids.reject(&:empty?).empty?
  end



  ## scopes
  def activities
    PublicActivity::Activity.where(unit_id: self.id).order('created_at DESC')
    # Unit.all
  end



  private

    # def save_original_filename
    #   puts "consent_form present: #{consent_form.present?}"
    #   if consent_form.present?
    #   end
    # end

    def update_consent_form_attributes
      return unless consent_form.present? && consent_form_changed?
      self.consent_form_original_file_name = consent_form.file.original_filename
      self.consent_form_updated_at = Time.zone.now
      self.consent_form_content_type = consent_form.file.content_type
      self.consent_form_file_size = consent_form.file.size
    end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :auth_and_time_zone
  # before_action :set_unit, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized


  def index
    authorize Unit
    @units = @unit
  end

  def show
    authorize @unit
  end

  def new
    @unit = Unit.new
    authorize @unit
  end

  def edit
    authorize @unit
  end

  def create
    authorize @unit
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to unit_events_url(@unit), notice: "#{@unit.unit_type_title} Settings were successfully created."
    else
      render action: :new
    end
  end

  def update
    authorize @unit
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      redirect_to unit_events_url(@unit), notice: "#{@unit.unit_type_title} Settings were successfully updated."
    else
      render action: :edit
    end
  end

  def destroy
    authorize @unit
    # @unit.destroy

    redirect_to units_url
  end

  def change_default_unit
    authorize Unit
    redirect_to unit_events_url(@unit)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    # def set_unit
    #   @unit = current_user.units.where(id: params[:id]).first
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(
        :address1, :address2, :city, :state, :zip_code, :time_zone, :attach_consent_form,
        :use_consent_form, :consent_form, :url_consent_form, :home_address1, :home_address2, :home_zip_code,
        :home_state, :home_city, :home_map_url, :home_name, { health_form_coordinator_ids: [] }
      )
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.haml
= bootstrap_form_for @unit do |f|
  = render partial: 'layouts/flash', locals: { flash: flash, ar_object: @unit }

  .row
    .col-md-6
      = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, help: 'all dates and times will be displayed in this time zone, for all users'

  %fieldset
    %legend Health Form Coordinators
    %p You can select users who are authorized to edit health form dates. Users with 'Leader' roles can not edit health form dates, you need to add them as coordinators.
    %p Users with 'Admin' roles can always edit health form dates.
    .row
      .col-md-8
        = f.collection_select :health_form_coordinator_ids, @unit.adults.by_name_lf, :id, :name_lf, { label: 'Health Form Coordinators' }, multiple: true, class: 'form-control'


  %fieldset
    %legend Activity Consent Form
    .row
      .col-md-8
        = f.check_box :attach_consent_form, label: 'Automatically attach consent form link to events that require ACF (recommended)'
        %br
        .indent-sub-selection
          = f.form_group :use_consent_form, label: { text: 'Select ACF to attach' } do
            %br
            = f.radio_button :use_consent_form, 1, label: 'Use current BSA Activity Consent Form', inline: true
            %a{ href: 'http://www.scouting.org/filestore/pdf/19-673.pdf' } (view BSA ACF)

            = f.radio_button :use_consent_form, 2, label: 'Use URL (link) to a page or form'
            .indent-sub-selection= f.text_field :url_consent_form, label: 'URL of custom consent form'

            = f.radio_button :use_consent_form, 3, label: 'Select custom consent form'
            .indent-sub-selection
              .well.well-sm
                %p= f.file_field :consent_form, hide_label: true, help: 'alowed attachments: jpg jpeg gif png pdf doc xls docx xls xlsx xlsb rtf odf txt'

                - if @unit.consent_form.present?
                  Current form:
                  = link_to @unit.consent_form_original_file_name, @unit.consent_form.url
                  %small (#{number_to_human_size @unit.consent_form_file_size}, #{@unit.consent_form_updated_at.to_s(:long_ampm)})



  %fieldset
    %legend Home Meeting Location
    %p Where you have your regular #{@unit.unit_type_title} Meetings. Setting this makes it easy to copy this location for meetings.
    .row
      .col-md-6
        = f.text_field :home_name, label: 'Name'
        = f.text_field :home_address1, label: 'Address1'
        = f.text_field :home_address2, label: 'Address2'
    .row
      .col-md-2
        = f.text_field :home_city, label: 'City'
      .col-md-2
        = f.select :home_state, options_for_select(::UsStates.states_array, @unit.state), include_blank: 'Select...'
      .col-md-2
        = f.text_field :home_zip_code, label: 'Zip'
    .row
      .col-md-8
        = f.text_field :home_map_url, label: 'Map URL', placeholder: 'http://maps.google.com', help: "if you don't enter a map url, the above address will be used to display a map"



  %fieldset
    %legend Mailing Address (optional)
    .row
      .col-md-6
        = f.text_field :address1, label: 'Address1'
        = f.text_field :address2, label: 'Address2'
    .row
      .col-md-2
        = f.text_field :city, label: 'City'
      .col-md-2
        = f.select :state, options_for_select(::UsStates.states_array, @unit.state), include_blank: 'Select...'
      .col-md-2
        = f.text_field :zip_code, label: 'Zip'


  %br
  = f.primary
  = link_to 'Cancel', unit_events_path(@unit), class: 'btn btn-default'

app/views/units/edit.html.haml
.page-header
  %h2 Edit #{@unit.unit_type_title} Settings

= render 'units/form'

app/views/units/index.html.haml
- model_class = Unit.new.class
%h1= t '.title', default: model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:unit_type)
      %th= model_class.human_attribute_name(:unit_number)
      %th= model_class.human_attribute_name(:city)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:time_zone)
      %th= t '.actions', default: t('helpers.actions')
  %tbody
    - @units.each do |unit|
      %tr
        %td= link_to unit.id, unit_path(unit)
        %td= unit.unit_type
        %td= unit.unit_number
        %td= unit.city
        %td= unit.state
        %td= unit.time_zone
        %td
          = link_to t('.edit', default: t('helpers.links.edit')), edit_unit_path(unit), class: 'btn btn-mini'
          = link_to t('.destroy', default: t('helpers.links.destroy')), unit_path(unit), method: :delete, confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')), class: 'btn btn-mini btn-danger'

= link_to t('.new', default: t('helpers.links.new')), new_unit_path, class: 'btn btn-primary'

app/views/units/new.html.haml
.page-header
	%h1 Setup your new unit

= render partial: "form"

app/views/units/show.html.haml
- model_class = @unit.class
%h1= t '.title', default: model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:unit_type) + ':'
  %br
  = @unit.unit_type
%p
  %strong= model_class.human_attribute_name(:unit_number) + ':'
  %br
  = @unit.unit_number
%p
  %strong= model_class.human_attribute_name(:city) + ':'
  %br
  = @unit.city
%p
  %strong= model_class.human_attribute_name(:state) + ':'
  %br
  = @unit.state
%p
  %strong= model_class.human_attribute_name(:time_zone) + ':'
  %br
  = @unit.time_zone

.form-group
  .col-md-offset-4.col-md-6
    = link_to t('.back', default: t('helpers.links.back')), units_path, class: 'btn btn-default'
    = link_to t('.edit', default: t('helpers.links.edit')), edit_unit_path(@unit), class: 'btn btn-default'
    = link_to t('.destroy', default: t('helpers.links.destroy')), unit_path(@unit), method: :delete, confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')), class: 'btn btn-danger'